# Generated by Django 4.2.7 on 2023-11-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_productos', '0001_initial'),
        ('productos', '0011_producto_departamento_producto_inventario_minimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_productos.tipoproducto'),
        ),
    ]
