# Generated by Django 4.2.7 on 2023-11-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_producto_precio_remove_producto_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='departamento',
            new_name='tipo',
        ),
    ]
