# Generated by Django 4.2.7 on 2023-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_rename_departamento_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_inventario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
