# Generated by Django 4.2.7 on 2023-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_alter_producto_cantidad_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='inventario_minimo',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
