# Generated by Django 4.2.7 on 2023-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_producto_inventario_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
