# Generated by Django 4.2.4 on 2023-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
